##form
POST http://localhost:3000/register
Content-Type:application/json

{
    "email":"anto54@gmail.com",
    "password":"Passw0rd!@",
    "repeatPassword":"Passw0rd!@",
    "firstName":"anto",
    "lastName":"nonloso",
    "tel":"123456789",
    "company":"google"
}


### delete table users
DELETE http://localhost:3000/delete
Content-Type:application/json